---@meta
---@diagnostic disable: lowercase-global
---@diagnostic disable: missing-return
--[[

This is a generated file. Do not modify. Created using https://github.com/britzl/generatedocs
--]]

---@class defold_api.wavedash_api
---@field EVENT_LOBBY_MESSAGE number
---@field EVENT_LOBBY_JOINED number
---@field EVENT_LOBBY_KICKED number
---@field EVENT_LOBBY_USERS_UPDATED number
---@field EVENT_LOBBY_DATA_UPDATED number
---@field EVENT_LOBBY_INVITE number
---@field EVENT_P2P_CONNECTION_ESTABLISHED number
---@field EVENT_P2P_CONNECTION_FAILED number
---@field EVENT_P2P_PEER_DISCONNECTED number
---@field EVENT_P2P_PEER_RECONNECTING number
---@field EVENT_P2P_PEER_RECONNECTED number
---@field EVENT_P2P_PACKET_DROPPED number
---@field EVENT_STATS_STORED number
---@field EVENT_BACKEND_CONNECTED number
---@field EVENT_BACKEND_DISCONNECTED number
---@field EVENT_BACKEND_RECONNECTING number
---@field EVENT_FULLSCREEN_CHANGED number
---@field LOBBY_VISIBILITY_PUBLIC number
---@field LOBBY_VISIBILITY_FRIENDS_ONLY number
---@field LOBBY_VISIBILITY_PRIVATE number
---@field LEADERBOARD_SORT_ORDER_ASC number
---@field LEADERBOARD_SORT_ORDER_DESC number
---@field LEADERBOARD_DISPLAY_TYPENUMERIC number
---@field LEADERBOARD_DISPLAY_TYPETIME_SECONDS number
---@field LEADERBOARD_DISPLAY_TYPETIME_MILLISECONDS number
---@field LEADERBOARD_DISPLAY_TYPETIME_GAME_TICKS number
---@field UGC_TYPE_SCREENSHOT number
---@field UGC_TYPE_VIDEO number
---@field UGC_TYPE_COMMUNITY number
---@field UGC_TYPE_GAME_MANAGED number
---@field UGC_TYPE_OTHER number
---@field UGC_VISIBILITY_PUBLIC number
---@field UGC_VISIBILITY_FRIENDS_ONLY number
---@field UGC_VISIBILITY_PRIVATE number
---@field AVATAR_SIZE_SMALL number
---@field AVATAR_SIZE_MEDIUM number
---@field AVATAR_SIZE_LARGE number
---@field LOBBY_KICKED_REASON_KICKED number
---@field LOBBY_KICKED_REASON_ERROR number
---@field LOBBY_USER_CHANGE_TYPE_JOINED number
---@field LOBBY_USER_CHANGE_TYPE_LEFT number
---@field P2P_PACKET_DROP_REASON_QUEUE_FULL number
---@field P2P_PACKET_DROP_REASON_PAYLOAD_TOO_LARGE number
---@field P2P_PACKET_DROP_REASON_INVALID_PAYLOAD_SIZE number
---@field P2P_PACKET_DROP_REASON_INVALID_CHANNEL number
---@field P2P_PACKET_DROP_REASON_MALFORMED number
---@field P2P_PACKET_DROP_REASON_PEER_NOT_READY number
wavedash_api = {}
---@param callback function
function wavedash_api.Wavedash_Init(callback) end
function wavedash_api.Wavedash_ReadyForEvents() end
---@param progress number
function wavedash_api.Wavedash_UpdateLoadProgressZeroToOne(progress) end
function wavedash_api.Wavedash_LoadComplete() end
function wavedash_api.Wavedash_ToggleOverlay() end
function wavedash_api.Wavedash_IsFullscreen() end
---@param fullscreen boolean
function wavedash_api.Wavedash_RequestFullscreen(fullscreen) end
function wavedash_api.Wavedash_ToggleFullscreen() end
function wavedash_api.Wavedash_GetUser() end
---@param @number? number
function wavedash_api.Wavedash_GetUsername(@number?) end
function wavedash_api.Wavedash_GetUserId() end
function wavedash_api.Wavedash_GetUserJwt() end
function wavedash_api.Wavedash_GetLaunchParams() end
function wavedash_api.Wavedash_ListFriends() end
---@param user_id number
---@param @number? number
function wavedash_api.Wavedash_GetUserAvatarUrl(user_id,@number?) end
---@param name string
function wavedash_api.Wavedash_GetLeaderboard(name) end
---@param name string
---@param sort_order number
---@param display_type number
function wavedash_api.Wavedash_GetOrCreateLeaderboard(name,sort_order,display_type) end
---@param leaderboard_id number
function wavedash_api.Wavedash_GetLeaderboardEntryCount(leaderboard_id) end
---@param leaderboard_id number
function wavedash_api.Wavedash_GetMyLeaderboardEntries(leaderboard_id) end
---@param leaderboard_id number
---@param count_ahead number
---@param count_behind number
---@param @boolean? boolean
function wavedash_api.Wavedash_ListLeaderboardEntriesAroundUser(leaderboard_id,count_ahead,count_behind,@boolean?) end
---@param leaderboard_id number
---@param offset number
---@param limit number
---@param @boolean? boolean
function wavedash_api.Wavedash_ListLeaderboardEntries(leaderboard_id,offset,limit,@boolean?) end
---@param leaderboard_id number
---@param score number
---@param keep_best boolean
---@param @number? number
function wavedash_api.Wavedash_UploadLeaderboardScore(leaderboard_id,score,keep_best,@number?) end
---@param ugc_type number
---@param @string? string
---@param @string? string
---@param @number? number
---@param @string? string
function wavedash_api.Wavedash_CreateUGCItem(ugc_type,@string?,@string?,@number?,@string?) end
---@param ugc_id number
---@param @string? string
---@param @string? string
---@param @number? number
---@param @string? string
function wavedash_api.Wavedash_UpdateUGCItem(ugc_id,@string?,@string?,@number?,@string?) end
---@param ugc_id number
---@param file_path string
function wavedash_api.Wavedash_DownloadUGCItem(ugc_id,file_path) end
---@param file_path string
function wavedash_api.Wavedash_DeleteRemoteFile(file_path) end
---@param file_path string
function wavedash_api.Wavedash_DownloadRemoteFile(file_path) end
---@param file_path string
function wavedash_api.Wavedash_UploadRemoteFile(file_path) end
---@param path string
function wavedash_api.Wavedash_ListRemoteDirectory(path) end
---@param path string
function wavedash_api.Wavedash_DownloadRemoteDirectory(path) end
---@param file_path string
---@param data string
function wavedash_api.Wavedash_WriteLocalFile(file_path,data) end
---@param file_path string
function wavedash_api.Wavedash_ReadLocalFile(file_path) end
---@param identifier string
function wavedash_api.Wavedash_GetAchievement(identifier) end
---@param identifier string
function wavedash_api.Wavedash_GetStat(identifier) end
---@param identifier string
---@param @boolean? boolean
function wavedash_api.Wavedash_SetAchievement(identifier,@boolean?) end
---@param identifier string
---@param value number
---@param @boolean? boolean
function wavedash_api.Wavedash_SetStat(identifier,value,@boolean?) end
function wavedash_api.Wavedash_RequestStats() end
function wavedash_api.Wavedash_StoreStats() end
function wavedash_api.Wavedash_GetP2PMaxPayloadSize() end
function wavedash_api.Wavedash_GetP2PMaxIncomingMessages() end
function wavedash_api.Wavedash_GetP2POutgoingMessageBuffer() end
---@param @number? number
---@param @number? number
---@param @boolean? boolean
---@param payload string
---@param @number? number
function wavedash_api.Wavedash_SendP2PMessage(@number?,@number?,@boolean?,payload,@number?) end
---@param @number? number
---@param @boolean? boolean
---@param payload string
---@param @number? number
function wavedash_api.Wavedash_BroadcastP2PMessage(@number?,@boolean?,payload,@number?) end
---@param app_channel number
function wavedash_api.Wavedash_ReadP2PMessageFromChannel(app_channel) end
---@param app_channel number
function wavedash_api.Wavedash_DrainP2PChannelToBuffer(app_channel) end
---@param visibility number
---@param max_players number
function wavedash_api.Wavedash_CreateLobby(visibility,max_players) end
---@param lobby_id number
function wavedash_api.Wavedash_JoinLobby(lobby_id) end
---@param @boolean? boolean
function wavedash_api.Wavedash_ListAvailableLobbies(@boolean?) end
---@param lobby_id number
function wavedash_api.Wavedash_GetLobbyUsers(lobby_id) end
---@param lobby_id number
function wavedash_api.Wavedash_GetNumLobbyUsers(lobby_id) end
---@param lobby_id number
function wavedash_api.Wavedash_GetLobbyHostId(lobby_id) end
---@param lobby_id number
---@param key string
function wavedash_api.Wavedash_GetLobbyData(lobby_id,key) end
---@param lobby_id number
---@param key string
function wavedash_api.Wavedash_SetLobbyData(lobby_id,key) end
---@param lobby_id number
---@param key string
function wavedash_api.Wavedash_DeleteLobbyData(lobby_id,key) end
---@param lobby_id number
function wavedash_api.Wavedash_LeaveLobby(lobby_id) end
---@param lobby_id number
---@param message string
function wavedash_api.Wavedash_SendLobbyMessage(lobby_id,message) end
---@param lobby_id number
---@param user_id number
function wavedash_api.Wavedash_InviteUserToLobby(lobby_id,user_id) end
---@param @boolean? boolean
function wavedash_api.Wavedash_GetLobbyInviteLink(@boolean?) end
---@param @string? string
function wavedash_api.Wavedash_UpdateUserPresence(@string?) end
function wavedash_api.Wavedash_EnsureGameplayJwt() end
