---@meta
---@diagnostic disable: lowercase-global
---@diagnostic disable: missing-return
--[[
Wavedash Defold API
This is a generated file. Do not modify. Created using https://github.com/britzl/generatedocs
--]]

---@class defold_api.wavedash
---@field EVENT_LOBBY_MESSAGE number
---@field EVENT_LOBBY_JOINED number
---@field EVENT_LOBBY_KICKED number
---@field EVENT_LOBBY_USERS_UPDATED number
---@field EVENT_LOBBY_DATA_UPDATED number
---@field EVENT_LOBBY_INVITE number
---@field EVENT_P2P_CONNECTION_ESTABLISHED number
---@field EVENT_P2P_CONNECTION_FAILED number
---@field EVENT_P2P_PEER_DISCONNECTED number
---@field EVENT_P2P_PEER_RECONNECTING number
---@field EVENT_P2P_PEER_RECONNECTED number
---@field EVENT_P2P_PACKET_DROPPED number
---@field EVENT_STATS_STORED number
---@field EVENT_BACKEND_CONNECTED number
---@field EVENT_BACKEND_DISCONNECTED number
---@field EVENT_BACKEND_RECONNECTING number
---@field EVENT_FULLSCREEN_CHANGED number
---@field LOBBY_VISIBILITY_PUBLIC number
---@field LOBBY_VISIBILITY_FRIENDS_ONLY number
---@field LOBBY_VISIBILITY_PRIVATE number
---@field LEADERBOARD_SORT_ORDER_ASC number
---@field LEADERBOARD_SORT_ORDER_DESC number
---@field LEADERBOARD_DISPLAY_TYPENUMERIC number
---@field LEADERBOARD_DISPLAY_TYPETIME_SECONDS number
---@field LEADERBOARD_DISPLAY_TYPETIME_MILLISECONDS number
---@field LEADERBOARD_DISPLAY_TYPETIME_GAME_TICKS number
---@field UGC_TYPE_SCREENSHOT number
---@field UGC_TYPE_VIDEO number
---@field UGC_TYPE_COMMUNITY number
---@field UGC_TYPE_GAME_MANAGED number
---@field UGC_TYPE_OTHER number
---@field UGC_VISIBILITY_PUBLIC number
---@field UGC_VISIBILITY_FRIENDS_ONLY number
---@field UGC_VISIBILITY_PRIVATE number
---@field AVATAR_SIZE_SMALL number
---@field AVATAR_SIZE_MEDIUM number
---@field AVATAR_SIZE_LARGE number
---@field LOBBY_KICKED_REASON_KICKED number
---@field LOBBY_KICKED_REASON_ERROR number
---@field LOBBY_USER_CHANGE_TYPE_JOINED number
---@field LOBBY_USER_CHANGE_TYPE_LEFT number
---@field P2P_PACKET_DROP_REASON_QUEUE_FULL number
---@field P2P_PACKET_DROP_REASON_PAYLOAD_TOO_LARGE number
---@field P2P_PACKET_DROP_REASON_INVALID_PAYLOAD_SIZE number
---@field P2P_PACKET_DROP_REASON_INVALID_CHANNEL number
---@field P2P_PACKET_DROP_REASON_MALFORMED number
---@field P2P_PACKET_DROP_REASON_PEER_NOT_READY number
wavedash = {}
---@param callback function
function wavedash.init(callback) end
function wavedash.ready_for_events() end
---@param progress number
function wavedash.update_load_progress_zero_to_one(progress) end
function wavedash.load_complete() end
function wavedash.toggle_overlay() end
function wavedash.is_fullscreen() end
---@param fullscreen boolean
function wavedash.request_fullscreen(fullscreen) end
function wavedash.toggle_fullscreen() end
function wavedash.get_user() end
---@param user_id number?
function wavedash.get_username(user_id) end
function wavedash.get_user_id() end
function wavedash.get_user_jwt() end
function wavedash.get_launch_params() end
function wavedash.list_friends() end
---@param user_id number
---@param size number?
function wavedash.get_user_avatar_url(user_id,size) end
---@param name string
function wavedash.get_leaderboard(name) end
---@param name string
---@param sort_order number
---@param display_type number
function wavedash.get_or_create_leaderboard(name,sort_order,display_type) end
---@param leaderboard_id number
function wavedash.get_leaderboard_entry_count(leaderboard_id) end
---@param leaderboard_id number
function wavedash.get_my_leaderboard_entries(leaderboard_id) end
---@param leaderboard_id number
---@param count_ahead number
---@param count_behind number
---@param friends_only boolean?
function wavedash.list_leaderboard_entries_around_user(leaderboard_id,count_ahead,count_behind,friends_only) end
---@param leaderboard_id number
---@param offset number
---@param limit number
---@param friends_only boolean?
function wavedash.list_leaderboard_entries(leaderboard_id,offset,limit,friends_only) end
---@param leaderboard_id number
---@param score number
---@param keep_best boolean
---@param ugc_id number?
function wavedash.upload_leaderboard_score(leaderboard_id,score,keep_best,ugc_id) end
---@param ugc_type number
---@param title string?
---@param description string?
---@param visibility number?
---@param file_path string?
function wavedash.create_ugc_item(ugc_type,title,description,visibility,file_path) end
---@param ugc_id number
---@param title string?
---@param description string?
---@param visibility number?
---@param file_path string?
function wavedash.update_ugc_item(ugc_id,title,description,visibility,file_path) end
---@param ugc_id number
---@param file_path string
function wavedash.download_ugc_item(ugc_id,file_path) end
---@param file_path string
function wavedash.delete_remote_file(file_path) end
---@param file_path string
function wavedash.download_remote_file(file_path) end
---@param file_path string
function wavedash.upload_remote_file(file_path) end
---@param path string
function wavedash.list_remote_directory(path) end
---@param path string
function wavedash.download_remote_directory(path) end
---@param file_path string
---@param data string
function wavedash.write_local_file(file_path,data) end
---@param file_path string
function wavedash.read_local_file(file_path) end
---@param identifier string
function wavedash.get_achievement(identifier) end
---@param identifier string
function wavedash.get_stat(identifier) end
---@param identifier string
---@param store_now boolean?
function wavedash.set_achievement(identifier,store_now) end
---@param identifier string
---@param value number
---@param store_now boolean?
function wavedash.set_stat(identifier,value,store_now) end
function wavedash.request_stats() end
function wavedash.store_stats() end
function wavedash.get_p2p_max_payload_size() end
function wavedash.get_p2p_max_incoming_messages() end
function wavedash.get_p2p_outgoing_message_buffer() end
---@param to_user_id number?
---@param app_channel number?
---@param reliable boolean?
---@param payload string
---@param payload_size number?
function wavedash.send_p2p_message(to_user_id,app_channel,reliable,payload,payload_size) end
---@param app_channel number?
---@param reliable boolean?
---@param payload string
---@param payload_size number?
function wavedash.broadcast_p2p_message(app_channel,reliable,payload,payload_size) end
---@param app_channel number
function wavedash.read_p2p_message_from_channel(app_channel) end
---@param app_channel number
function wavedash.drain_p2p_channel_to_buffer(app_channel) end
---@param visibility number
---@param max_players number
function wavedash.create_lobby(visibility,max_players) end
---@param lobby_id number
function wavedash.join_lobby(lobby_id) end
---@param friends_only boolean?
function wavedash.list_available_lobbies(friends_only) end
---@param lobby_id number
function wavedash.get_lobby_users(lobby_id) end
---@param lobby_id number
function wavedash.get_num_lobby_users(lobby_id) end
---@param lobby_id number
function wavedash.get_lobby_host_id(lobby_id) end
---@param lobby_id number
---@param key string
function wavedash.get_lobby_data(lobby_id,key) end
---@param lobby_id number
---@param key string
function wavedash.set_lobby_data(lobby_id,key) end
---@param lobby_id number
---@param key string
function wavedash.delete_lobby_data(lobby_id,key) end
---@param lobby_id number
function wavedash.leave_lobby(lobby_id) end
---@param lobby_id number
---@param message string
function wavedash.send_lobby_message(lobby_id,message) end
---@param lobby_id number
---@param user_id number
function wavedash.invite_user_to_lobby(lobby_id,user_id) end
---@param copy_to_clipboard boolean?
function wavedash.get_lobby_invite_link(copy_to_clipboard) end
---@param data_json string?
function wavedash.update_user_presence(data_json) end
function wavedash.ensure_gameplay_jwt() end
